# Generated by Django 4.0.5 on 2022-06-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_game_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='content',
            field=models.TextField(blank=True, help_text="separate each content with '|' (AC Valhalla|AC Valhalla: Aube du Ranarok)", null=True, verbose_name='contenus'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
